# Generated by Django 4.2.1 on 2023-05-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starmart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
